add_rules("mode.debug", "mode.release")
add_requires("glog", "gflags", "pybind11")

target("ctp_se_market")
    add_packages("glog", "gflags")
    set_kind("binary")
    add_includedirs("include")
    -- add_linkdirs("lib")
    set_warnings("all", "error")
    set_languages("c++17")
    add_files("src/*.cc")
    add_ldflags("-Llib/", "-lpthread", "-lthostmduserapi_se", {force = true})

target("mmap_reader")
    add_packages("glog", "gflags")
    set_kind("shared")
    add_includedirs("src")
    add_files("src/pybind/*.cc")
    set_languages("c++17")
    add_packages("pybind11")
